### ISSUE TITLE
Limit users to see the own dedicated task

### ISSUE THREAD

**Issue by allogos** [projectknife/Projectfork#1799] opened 2017-01-12 12:04 UTC
Hi, 

How can i limit users to see the only task they are assigned for. Right now user can see all other task in same project which is assigned to other people!

for example in Project (A) we have 3 tasks 1,2 and 3.
user A assign to task 1.
user B assign to task 2&3.

I don't want user user A able to see User B tasks.

Thanks

**Comment by angek** [comment] 2017-07-31 02:56
Yes, this is the intended behaviour. If you are a member of a specific project team then you can see all its tasks. There is no option to limit this display to show only the tasks assigned to the logged in user.
I believe this is possible with Projectknife.

**Closed by angek** 2017-07-31 02:56 UTC
